user: CVPR2025-761
project_name: MIRAGE
seed: 114514
debug: false
running_time: ${now:%Y-%m-%d-%H-%M-%S}
num_workers: 16
tags: 
work_dir: ${hydra:runtime.cwd}
image_size: 224
hydra:
  output_subdir: hydra
  run:
    dir: ../logs/${experiment_name}
  job:
    env_set: 
      TOKENIZERS_PARALLELISM: "false"
      
